### ISSUE TITLE
Multiclass Segmentation

### ISSUE THREAD

**Issue by Oushesh** [Cheng-Lin-Li/SegCaps#1]
Hi Cheng-Lin-Li,

I found your modification of this repo really good, specially the adaptions for training on MS Coco Dataset. Nevertheless, did you also perform on images with more than 2 classes apart from binary segmentation?

Thanks man!
Cheers,
Oushesh

**Comment by Cheng-Lin-Li** [comment]
Hi Oushesh,

Due to resource constraint, I did not enhance the model to support the multiclass classification task. But it is doable. Try to fork my repo and revise it. It is also welcome if you want to contribute the repo.

Kind regards,
Cheng-Lin

**Comment by Oushesh** [comment]
Hi Cheng-Li,

Thanks for your reply. I meant multi class segmentation.

I reckon it support since I saw you can also extract MS Coco multiclass
datasets

**Comment by Cheng-Lin-Li** [comment]
Hi Oushesh:

 

The model so far just support binary class segmentation but it is doable for multiclass segmentation task.

It is required to change the last few layers, reconstruction , loss function and metrics and so on to keep it compatible with CT images.

So far I run out of my resource to do the enhancement but you may try.

 

Thanks with kind regards,

 

Cheng-Lin Li

Graduate Student of Data Informatics

Viterbi School of Engineering

University of Southern California

**Comment by Cheng-Lin-Li** [comment]
Hi Oushesh:

Due to this is an enhancement request rather than a bug, I put the request in the TODO list on readme and close it.

Thanks with kind regards,
Cheng-Lin
