### ISSUE TITLE
Creating MSCOCO dataset

### ISSUE THREAD

**Issue by shan18** [Cheng-Lin-Li/SegCaps#10]
How did you create the label vector (y) when using the model on MSCOCO dataset? For each input (image), MSCOCO has multiple outputs (categories). How to create the dataset in this case (i.e. the input vector x and the label vector y)?
Any help would be appreciated. Thank You.

**Comment by Cheng-Lin-Li** [comment]
Hi Shan18,

You may try to look into my implementation of MSCOCO crawler.
https://github.com/Cheng-Lin-Li/SegCaps/blob/master/cococrawler/getcoco17.py

pycocotools.coco provide API to let you identify the annotation for each category of an instance.
My implementation performs binary classification, the output mask file (y) only contain 0 or 1 for each pixel. You can define a value index to match with your categories.

**Comment by shan18** [comment]
Okay, thank you for the help.
