### ISSUE TITLE
Instruction for running the code from .jpg files

### ISSUE THREAD

**Issue by hiteshnitetc** [Cheng-Lin-Li/SegCaps#12]
Hello, i have put images and into .jpg and mask under imgs and ans masks folder respectively. after running code getting some error which is mentioned into following figure, how to run your code. My images are gray scale. and os is ubuntu 16.04
![Screenshot from 2019-07-04 18-05-42](https://user-images.githubusercontent.com/30615882/60672663-92b18780-9e93-11e9-9304-28774bbf9887.png)

**Comment by Cheng-Lin-Li** [comment]
Dear hiteshnitetc,

Did you put any image mask file in project folder/data/masks folder?

**Comment by hiteshnitetc** [comment]
Yes, I have put 10 images in data/imgs folder and mask images in data/masks folder

**Comment by Cheng-Lin-Li** [comment]
Hi hiteshnitetc,

According to the error message, the program cannot find mask files in the folder.
You can trace the code and see the reason behind it.

By the way, I saw your another issue ticket which looks like you already solve this issue.
I will close this issue but let me know if you would like to reopen it.
