### ISSUE TITLE
input size

### ISSUE THREAD

**Issue by avassadi** [Cheng-Lin-Li/SegCaps#6]
Hello,
my data is 3D volumes with dimensions of (217, 181, 50). In the readme, you mentioned that the code can handle to input size itself, but I get this error:
"ValueError: could not broadcast input array from shape (217,181,50) into shape (512,512,1)".
Another issue is when trying to load my own data, load_2d_data invokes, although my data is 3D.
Is there anything that I should take care of?
Thank you

**Comment by Cheng-Lin-Li** [comment]
Hi Avassadi,

It looks like the program treats the input as 2D images rather than 3D.
May I know what parameters you use for the program?

**Comment by avassadi** [comment]
Thank you for the quick response. these are my parameters:
--data_root_dir  my/path/to/data
--test --net segcapsr3 --save_raw 1 --save_seg 1

**Comment by Cheng-Lin-Li** [comment]
Hi Avassadi,

You may try to add '--dataset luna16' to try for 3D images.
By the way, did you complete training without error? The '--test' flag is for testing on pre-trained model.
