### ISSUE TITLE
expected out_recon  shape (512, 512, 1)

### ISSUE THREAD

**Issue by AloshkaD** [Cheng-Lin-Li/SegCaps#9]
I'm training CapsNetR3 on my own dataset. I get the following error

`Error when checking target: expected out_recon to have shape (512, 512, 1) but got array with shape (512, 512, 3)`

my input shape is 512, 512, 3. Any clue or hint is highly appreciated

**Comment by AloshkaD** [comment]
I solved it with by changing the filter size from 1 to 3 
`out_recon = layers.Conv2D(filters=3, kernel_size=1, padding='same', kernel_initializer='he_normal',
                                  activation='sigmoid', name='out_recon')(recon_2)
`

**Comment by Cheng-Lin-Li** [comment]
Hi AloshkaD,

Thanks for sharing me the update.
My implementation remaps RGB 3 channels to 1 channel with 24 bits to avoid the changing of network structure. I guess you may do something else.
Glad you find the solution.

Kr,
Cheng-Lin Li
